<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>MVC toujours plus haut</title>
  <link rel="stylesheet" href="./assets/styles/style.css">
</head>

<body>

  <nav>
    <li><a href="index.php?route=list_user">List of users</a></li>
    <li><a href="index.php?route=create_user_form">Create a new user</a></li>
  </nav>

  <?php
  // contenu du body dynamique en fonction de $layoutContent, ça veux dire cependant qu'on se contraint 
  // à declarer $layoutContent avant de require ce fichier.
  switch ($layoutContent) {

    case 'create_user_form':
      require './templates/users/create.phtml';
      break;
    case 'update_user_form':
      require './templates/users/update.phtml';
      break;
    case 'list_user':
      require './templates/users/list.phtml';
    default:

      break;
  }
  ?>
</body>

</html>