<main>
  <h1>Create and add a user to the dataBase</h1>

  <form action="index.php?route=check_create_user" method="post">

    <label for="email">Email</label>
    <input type="email" name="email" id="email">
    <br />
    <label for="first_name">First Name</label>
    <input type="text" name="first_name" id="first_name">
    <br />
    <label for="last_name">Last Name</label>
    <input type="text" name="last_name" id="last_name">
    <br />
    <button type="submit">Create</button>
  </form>
</main>